### ISSUE TITLE
Help while casting PXWindowChanges to TXWindowChanges

### ISSUE THREAD

**Issue by Eduarch42** [nim-lang/x11#18]
I dont know if this place is the correct one to post this, but help is appreciated.

This is the case, im trying to code a window manager with this bindings and obviously Nim. I taking this example:

```C

static void
handle_configure_request(XEvent *e) 
{
    struct client *c;
    XConfigureRequestEvent *ev = &e->xconfigurerequest;
    XWindowChanges wc;

    fprintf(stderr, "Handling configure request event\n");

    wc.x = ev->x;
    wc.y = ev->y;
    wc.width = ev->width;
    wc.height = ev->height;
    wc.border_width = ev->border_width;
    wc.sibling = ev->above;
    wc.stack_mode = ev->detail;
    XConfigureWindow(display, ev->window, ev->value_mask, &wc);
    c = get_client_from_window(ev->window);

    if (c != NULL)
        refresh_client(c);
}
```

btw this is c code, the handler function for when a configure request happens. My best shot at porting this to Nim was this:

```nim

proc handleConfigureRequest(event: TXEvent) =

  var
    e: TXConfigureRequestEvent = event.xconfigurerequest
    wc: TXWindowChanges
    

  wc = TXWindowChanges(x: e.x, y: e.y, width: e.width, height: e.height,
   border_width: e.border_width, sibling: e.above, stack_mode: e.detail)


  var wcp* = cast[PXWindowChanges](wc)

  discard XConfigureWindow(display, e.window, cast[cuint](e.value_mask), wcp)
```

I thought everything was alright but when i run it, it crashes with the following message:
Error: expression cannot be cast to PXWindowChanges=ptr TXWindowChanges

How can i solve it? Disclaimer: The code blocks were all messy, so used my improvised blocks instead. Thanks!

**Comment by Araq** [comment]
```nim

var wcp = addr wc
```

Please read some tutorial about Nim.

**Comment by Eduarch42** [comment]
Thanks a lot, from now on will read more tutorials about Nim.
