### ISSUE TITLE
Type size mismatch with C

### ISSUE THREAD

**Issue by kitech** [nim-lang/x11#20]
Some type like TXIM, TXIC just defined as object, it not match the C type size.
Take a quick look, this way is used for other more type. Is that any special reason ?

**Comment by krux02** [comment]
Well this mapping is incorrect. This is the correct way to import C types with size:

```nim
type
  TXIM* {.final, importc:"XIM", header: "X11/Xlib.h".} = object

echo sizeof(TXIM)
```
