### ISSUE TITLE
Error: cannot open file: x

### ISSUE THREAD

**Issue by TensorTom** [nim-lang/x11#22]
On import I get Error: cannot open file: x with new version 0.20.0. This is only happening with x11 package.

**Comment by TensorTom** [comment]
if I try to run the example, I get:
xtest.nim(1, 8) Error: cannot open file: xlib

**Comment by trustable-code** [comment]
I guess the problem is that the source file ``xlib.nim`` is not in your library paths.
I think ``srcDir = "x11"`` should be added to https://github.com/nim-lang/x11/blob/master/x11.nimble

**Comment by dom96** [comment]
``import x11/x``
