### ISSUE TITLE
Example doesn't compile with current imports

### ISSUE THREAD

**Issue by MrOneTwo** [nim-lang/x11#24]
I tried to compile the example but it can't find `libx`.
I changed:

```nim
import xlib, xutil, x, keysym
```

to

```nim
import x11/xlib, x11/xutil, x11/x, x11/keysym
```

and that fixed it. Is it problem with the lib or is it something with my setup (I'm pretty new to nim)?

**Comment by Araq** [comment]
It's a valid bug report, at some point we introduced the ``x11`` subdir.
