### ISSUE TITLE
Error: -1 can't be converted to culong

### ISSUE THREAD

**Issue by dariolah** [nim-lang/x11#27]
Problem while using module **opengl**, dependencie is **x11**
It worked wih Nim 0.20.2. now it fails with 1.0

Hint: xlib [Processing]
/home/dlah/.nimble/pkgs/x11-1.1/x11/**xlib.nim(1121, 30) Error: -1 can't be converted to culong**

**Comment by krux02** [comment]
this one has been fixed already https://github.com/nim-lang/x11/blob/master/x11/xlib.nim#L1121
