### ISSUE TITLE
X11 object file might be named wrong

### ISSUE THREAD

**Issue by GraydenH** [nim-lang/x11#8]
Compiled my program x11 as a nimble dep with `nimble c --threads:on --noMain -d:nimDebugDlOpen test.nim`. When I run it it gets a runtime error saying it can't find libx11.so on my computer. I looked and the file is actually there named libx11.so.6 on my computer (openSuSE). A quick google search showed libx11.so.6 is a common name for the file, at least it is for ubuntu too.

I changed the file x11pragma.nim to open libx11.so.6 instead and the error went away.

I'm a linux noob, but should this be changed? Could a when statement be added for linux/appropriate distros to use this file?

**Comment by dom96** [comment]
yes. Let's change it. Best to support both filenames, so change it to ``"libX11.so(|.6)"`` (http://nim-lang.org/docs/manual.html#foreign-function-interface-dynlib-pragma-for-import). Could you create a PR for this? :)

**Comment by GraydenH** [comment]
https://github.com/nim-lang/x11/pull/9 PR created

**Comment by dom96** [comment]
Thanks!
